on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Repository Name: ${{ github.event.pull_request.head.repo.full_name }} Try it on Eclipse Che hosted by Red Hat https://workspaces.openshift.com#https://github.com/fork/${{ github.event.repository.name }}/tree/${{ github.head_ref }} [![Contribute](https://raw.githubusercontent.com/redhat-developer-demos/quarkus-reactjs-postit-app/master/factory-contribute.svg)] (https://workspaces.openshift.com#https://github.com/ibuziuk/che-docs/tree/che-19271) ![Eclipse Che hosted by Red Hat](https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
